config/routes.rb
Rails.application.routes.draw do
  get 'demo' => 'arabic_to_roman#index'

  resources :users

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :login, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/arabic_to_roman_controller.rb
class ArabicToRomanController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/arabic_to_roman/index.html.erb
<h1>Convert arabic number to roman!</h1>
<br>
<br>
<h2>Put your number here:</h2>

<form class="new_user" id="new_user" action="/users" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="TRUgDMawvK9S+NUrEGIEuMRt4DIIAlisgM/SFUJknEprMk0eTdVxk241zk+TI6o+JeY3md9qswHXmWIkjsJUIA==" />

  <div class="row">
    <div class="small-2 columns">
      <input placeholder="Enter number here" type="number" name="user[login]" id="user_login" value="8"/>
    </div>
  </div>

</form>

<h1>8 = VIII</h1>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
        <div class="row">
          <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %> large-4 columns text-center">
            <%= content_tag :div, msg %>
            <a href="#" class="close">&times;</a>
          </div>
        </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <!--<li class="name"><%= link_to 'Home', root_path %></li>-->
    <!--<li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>-->
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li>
  <%= link_to 'Users', users_path %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Feature Tests Demo" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Foundation" %>">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%# Modernizr is required for Zurb Foundation %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="margin-bottom-2">
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
  <div class="row">
    <div class="large-12 columns">
      <%= render 'layouts/messages' %>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= yield %>
    </div>
  </div>
</main>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="small-6 columns">
        <%= f.text_field :login, placeholder: 'Enter your login' %>
      </div>
    </div>

    <div class="row">
      <div class="small-6 columns">
        <%= f.text_field :email, placeholder: 'Enter your email' %>
      </div>
    </div>

    <div class="row">
      <div class="small-6 columns">
        <div class="small-6 columns small-centered text-center">
          <%= f.submit class: 'success button' %>
        </div>
      </div>
    </div>

    <div class="margin-bottom-1"></div>
<% end %>

app/views/users/edit.html.erb
<h2 class="margin-bottom-2">Edit User profile</h2>

<%= render 'form' %>

<ul class="button-group">
  <li>
    <%= link_to 'Back', users_path, class: 'button small inline left' %>
  </li>
  <li>
    <%= link_to 'Show', user_path(@user), class: 'button small inline right' %>
  </li>
</ul>

app/views/users/index.html.erb
<h2 class="margin-bottom-2">Listing Users</h2>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "button small" %>

app/views/users/new.html.erb
<h2 class="margin-bottom-2">Create new User</h2>

<%= render 'form' %>

<ul class="button-group">
  <li>
    <%= link_to 'Back', users_path, class: 'button small inline left' %>
  </li>
</ul>

app/views/users/show.html.erb
<h2 class="margin-bottom-2">User Profile</h2>

<table class="margin-bottom-2">
  <tr>
    <td>
      <strong>Login:</strong>
    </td>
    <td>
      <%= @user.login %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Email:</strong>
    </td>
    <td>
      <%= @user.email %>
    </td>
  </tr>
</table>

<ul class="button-group">
  <li>
    <%= link_to 'Back', users_path, class: 'button small inline left' %>
  </li>
  <li>
    <%= link_to 'Edit', edit_user_path(@user), class: 'button small inline right' %>
  </li>
</ul>